In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("vic_año-hab.csv")

In [3]:
url = "https://datosmacro.expansion.com/demografia/poblacion/espana-comunidades-autonomas"

hab = pd.read_html(url)[0]

v_año=pd.read_csv("victimas_por_año.csv")

In [4]:
hab

                        CCAA  Densidad  Población  Población.1    Var.
0              Andalucía [+]    98.000  8.600.224          NaN   0,30%
1                 Aragón [+]    28.000  1.354.144          NaN   0,36%
2               Asturias [+]    95.000  1.006.558          NaN   0,04%
3              Cantabria [+]   111.000    589.279          NaN   0,17%
4                  Ceuta [+]     4.142     82.831          NaN  -0,06%
5        Castilla y León [+]    25.000  2.383.702          NaN   0,09%
6     Castilla-La Mancha [+]    26.000  2.089.074          NaN   0,42%
7               Canarias [+]   299.000  2.224.343          NaN   0,56%
8               Cataluña [+]   248.000  7.970.295          NaN   0,94%
9            Extremadura [+]    25.000  1.053.463          NaN  -0,08%
10               Galicia [+]    91.000  2.699.938          NaN   0,03%
11        Islas Baleares [+]   245.000  1.220.739          NaN   1,11%
12      Región de Murcia [+]   138.000  1.560.347          NaN   0,52%
13   Comunidad de Madrid [+]   862.000  6.917.111          NaN   1,00%
14               Melilla [+]     7.135     85.622          NaN  -0,05%
15               Navarra [+]    65.000    674.796          NaN   0,44%
16            País Vasco [+]   307.000  2.224.072          NaN   0,23%
17              La Rioja [+]    64.000    323.377          NaN   0,34%
18  Comunidad Valenciana [+]   227.000  5.268.012          NaN   1,00%

In [5]:
poblacion = {"poblacion":[8600224, 1354144, 2224343, 2383702, 2089074, 7970295, 674796, 6917111, 5268012,
                         2699938, 323377, 2224072, 1560347 ]   
}

In [6]:
columna = pd.DataFrame(poblacion)

In [7]:
df = df.join(columna)

In [8]:
df

            comunidad_autonoma  n_victimas_mortales  poblacion
0                    Andalucía                 17.0    8600224
1                       Aragón                  1.0    1354144
2                     Canarias                  3.0    2224343
3              Castilla y León                  3.0    2383702
4           Castilla-La Mancha                  2.0    2089074
5                     Cataluña                 10.0    7970295
6   Comunidad Foral de Navarra                  1.0     674796
7          Comunidad de Madrid                  7.0    6917111
8         Comunitat Valenciana                  6.0    5268012
9                      Galicia                  3.0    2699938
10                    La Rioja                  1.0     323377
11                  País Vasco                  2.0    2224072
12            Región de Murcia                  1.0    1560347

In [10]:
victimas_por_cada_M_hab = df["n_victimas_mortales"] / df["poblacion"] * 1000000

In [11]:
data = pd.DataFrame(victimas_por_cada_M_hab)

In [12]:
data.rename(columns={0:"victimas_por_cada_M_hab"}, inplace=True)

In [13]:
df = df.join(data)

In [14]:
df.n_victimas_mortales=df.n_victimas_mortales.astype(int)

In [15]:
df.victimas_por_cada_M_hab=df.victimas_por_cada_M_hab.round(2)

In [16]:
df

,comunidad_autonoma,n_victimas_mortales,poblacion,victimas_por_cada_M_hab
0,Andalucía,17,8600224,1.98
1,Aragón,1,1354144,0.74
2,Canarias,3,2224343,1.35
3,Castilla y León,3,2383702,1.26
4,Castilla-La Mancha,2,2089074,0.96
5,Cataluña,10,7970295,1.25
6,Comunidad Foral de Navarra,1,674796,1.48
7,Comunidad de Madrid,7,6917111,1.01
8,Comunitat Valenciana,6,5268012,1.14
9,Galicia,3,2699938,1.11
10,La Rioja,1,323377,3.09
11,País Vasco,2,2224072,0.90
12,Región de Murcia,1,1560347,0.64

In [17]:
v_año

,comunidad_autonoma,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Andalucía,11.0,11.0,14.0,5.0,7.0,12.0,15.0,10.0,9.0,11.0,17.0
1,Aragón,2.0,0.0,1.0,3.0,0.0,4.0,1.0,0.0,2.0,2.0,1.0
2,Canarias,2.0,1.0,3.0,4.0,5.0,3.0,9.0,4.0,0.0,2.0,3.0
3,Cantabria,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0
4,Castilla y León,4.0,3.0,2.0,6.0,0.0,2.0,3.0,1.0,4.0,3.0,3.0
5,Castilla-La Mancha,4.0,0.0,1.0,1.0,6.0,2.0,0.0,4.0,1.0,7.0,2.0
6,Cataluña,4.0,13.0,6.0,6.0,8.0,9.0,8.0,8.0,11.0,8.0,10.0
7,Ceuta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8,Comunidad Foral de Navarra,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,1.0,1.0
9,Comunidad de Madrid,9.0,7.0,4.0,3.0,7.0,5.0,6.0,3.0,7.0,7.0,7.0
10,Comunitat Valenciana,9.0,7.0,11.0,6.0,7.0,2.0,7.0,7.0,7.0,3.0,6.0
11,Extremadura,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
12,Galicia,3.0,5.0,7.0,4.0,2.0,3.0,3.0,4.0,1.0,0.0,3.0
13,Illes Balears,2.0,3.0,1.0,6.0,0.0,2.0,1.0,3.0,2.0,0.0,0.0
14,La Rioja,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
15,Melilla,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,País Vasco,1.0,3.0,3.0,1.0,2.0,2.0,0.0,1.0,2.0,1.0,2.0
17,Principado de Asturias,1.0,0.0,3.0,2.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0
18,Región de Murcia,0.0,0.0,1.0,0.0,3.0,2.0,1.0,2.0,0.0,2.0,1.0